services:
  app:
    build: .
    environment:
      DISPLAY_WIDTH: ${DISPLAY_WIDTH:-1600}
      DISPLAY_HEIGHT: ${DISPLAY_HEIGHT:-900}
      RDP_HOST: ${RDP_HOST:-127.0.0.1}
      RDP_PORT: ${RDP_PORT:-3389}
      RDP_USERNAME: ${RDP_USERNAME:-user}
      RDP_PASSWORD: ${RDP_PASSWORD:-password}
    ports:
      - ${NOVNC_HOST:-127.0.0.1}:${NOVNC_PORT:-8080}:8080
